cmake_minimum_required(VERSION 3.22)

# Inspect ELF metadata without executing the binary or loading its dependencies.
execute_process(
    COMMAND "${READELF}" --wide --program-headers --dynamic "${BINARY}"
    RESULT_VARIABLE _result OUTPUT_VARIABLE _elf ERROR_VARIABLE _error
)
if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Cannot inspect ${BINARY}: ${_error}")
endif()
if(NOT _elf MATCHES "Requesting program interpreter: [^\n]*ld-linux-(x86-64\\.so\\.2|aarch64\\.so\\.1)")
    message(FATAL_ERROR "Expected dynamically linked x86-64 or ARM64 glibc in ${BINARY}.")
endif()
string(REGEX MATCHALL "Shared library: \\[[^]]+\\]" _needed "${_elf}")
if(NOT "Shared library: [libc.so.6]" IN_LIST _needed)
    message(FATAL_ERROR "Expected dynamic libc.so.6 dependency in ${BINARY}.")
endif()
if(DEPENDENCY_MODE STREQUAL "DISTRIBUTION")
    # Runtime dependency metadata is generated by distribution packaging tools.
    return()
elseif(NOT DEPENDENCY_MODE STREQUAL "DIRECT")
    message(FATAL_ERROR "Unknown dependency mode: ${DEPENDENCY_MODE}")
endif()
foreach(_entry IN LISTS _needed)
    if(NOT _entry MATCHES
       "^Shared library: \\[(lib(c|m|pthread|dl|rt|resolv|util|anl)\\.so\\.[0-9]+|ld-linux-(x86-64\\.so\\.2|aarch64\\.so\\.1))\\]$")
        message(FATAL_ERROR "Non-glibc shared dependency must be linked statically: ${_entry}")
    endif()
endforeach()
