cmake_minimum_required(VERSION 3.22)
if(NOT EXISTS "${BUILD_DIRECTORY}/tired" OR NOT EXISTS "${BUILD_DIRECTORY}/tired-helper")
    message(FATAL_ERROR "Build both qualified Release executables before packaging.")
endif()
find_program(SNAP_PACK snap REQUIRED)
find_program(PATCHELF patchelf REQUIRED)
if(ARCHITECTURE STREQUAL "amd64")
    set(_interpreter "/snap/core22/current/lib64/ld-linux-x86-64.so.2")
    set(_base_library_directory "/snap/core22/current/lib/x86_64-linux-gnu")
elseif(ARCHITECTURE STREQUAL "arm64")
    set(_interpreter "/snap/core22/current/lib/ld-linux-aarch64.so.1")
    set(_base_library_directory "/snap/core22/current/lib/aarch64-linux-gnu")
else()
    message(FATAL_ERROR "Snap packaging supports amd64 and arm64 only.")
endif()
set(_stage "${BUILD_DIRECTORY}/snap-stage")
file(REMOVE_RECURSE "${_stage}")
file(MAKE_DIRECTORY "${_stage}/meta")
execute_process(COMMAND "${CMAKE_COMMAND}" -E env "DESTDIR=${_stage}"
    "${CMAKE_COMMAND}" --install "${BUILD_DIRECTORY}" --prefix /usr/local
    RESULT_VARIABLE _installed)
if(NOT _installed EQUAL 0)
    message(FATAL_ERROR "Cannot stage the complete direct payload.")
endif()
foreach(_executable usr/local/bin/tired usr/local/libexec/tired/tired-helper)
    execute_process(COMMAND "${PATCHELF}" --set-interpreter "${_interpreter}"
        --force-rpath --set-rpath "${_base_library_directory}" "${_stage}/${_executable}"
        RESULT_VARIABLE _patched)
    if(NOT _patched EQUAL 0)
        message(FATAL_ERROR "Cannot configure the core22 runtime for ${_executable}.")
    endif()
endforeach()
configure_file("${BUILD_DIRECTORY}/snap.yaml" "${_stage}/meta/snap.yaml" COPYONLY)
execute_process(COMMAND "${SNAP_PACK}" pack "${_stage}" "${BUILD_DIRECTORY}"
    --filename "tired_${VERSION}_${ARCHITECTURE}.snap" RESULT_VARIABLE _packed)
if(NOT _packed EQUAL 0)
    message(FATAL_ERROR "Snap packing failed.")
endif()
