cmake_minimum_required(VERSION 3.22)
foreach(_required IN ITEMS SOURCE_PACKAGES OUTPUT_DIRECTORY VERSION)
    if(NOT DEFINED ${_required})
        message(FATAL_ERROR "Set ${_required} for corresponding-source packaging.")
    endif()
endforeach()
file(GLOB _descriptions "${SOURCE_PACKAGES}/*.dsc")
foreach(_instruction IN ITEMS cmake/PrepareSystemd.cmake BUILD.md)
    if(NOT EXISTS "${SOURCE_PACKAGES}/${_instruction}")
        message(FATAL_ERROR "Missing corresponding-source preparation instructions: ${_instruction}.")
    endif()
endforeach()
foreach(_required IN ITEMS systemd libgcrypt20 libgpg-error)
    file(GLOB _match "${SOURCE_PACKAGES}/${_required}_*.dsc")
    if(NOT _match)
        message(FATAL_ERROR "Missing exact LGPL corresponding source: ${_required}.")
    endif()
endforeach()
foreach(_description IN LISTS _descriptions)
    file(READ "${_description}" _text)
    string(REGEX MATCH "Checksums-Sha256:\n(( [^\n]+\n)+)" _block "${_text}")
    if(NOT _block)
        message(FATAL_ERROR "Missing source checksums in ${_description}.")
    endif()
    string(REGEX MATCHALL " [0-9a-f]+ [0-9]+ [^\n]+" _rows "${_block}")
    foreach(_row IN LISTS _rows)
        string(REGEX REPLACE "^ ([0-9a-f]+) [0-9]+ ([^\n]+)$" "\\1;\\2" _pair "${_row}")
        list(GET _pair 0 _expected)
        list(GET _pair 1 _file)
        if(_file MATCHES "[/\\\\]" OR NOT EXISTS "${SOURCE_PACKAGES}/${_file}")
            message(FATAL_ERROR "Missing/unsafe source archive ${_file}.")
        endif()
        file(SHA256 "${SOURCE_PACKAGES}/${_file}" _actual)
        if(NOT _actual STREQUAL _expected)
            message(FATAL_ERROR "Source checksum mismatch: ${_file}.")
        endif()
    endforeach()
endforeach()
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
get_filename_component(_source_name "${SOURCE_PACKAGES}" NAME)
get_filename_component(_source_parent "${SOURCE_PACKAGES}" DIRECTORY)
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar czf
    "${OUTPUT_DIRECTORY}/tired-${VERSION}-dependency-sources.tar.gz" "${_source_name}"
    WORKING_DIRECTORY "${_source_parent}" RESULT_VARIABLE _packed)
if(NOT _packed EQUAL 0)
    message(FATAL_ERROR "Cannot package verified corresponding sources.")
endif()
